name: "SWE 637"

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Compile Test for duplicateCoordinatesAtBaseOrAdjNode
        run: mvn clean install -DskipTests -pl core -am
      - name: Run Test Without Nondex Command
        run: mvn -pl core test -Dtest=com.graphhopper.routing.DirectionResolverOnQueryGraphTest#duplicateCoordinatesAtBaseOrAdjNode     
    
